# Generated by Django 5.0.2 on 2024-02-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkelement',
            name='element_type',
            field=models.CharField(choices=[('Factory', 'Завод'), ('RetailNetwork', 'Розничная сеть'), ('IndividualEntrepreneur', 'Индивидуальный предприниматель')], max_length=50),
        ),
    ]
