# Generated by Django 5.0.2 on 2024-02-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_networkelement_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkelement',
            name='city',
            field=models.CharField(max_length=50, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='country',
            field=models.CharField(max_length=50, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='element_type',
            field=models.CharField(choices=[('Factory', 'Завод'), ('RetailNetwork', 'Розничная сеть'), ('IndividualEntrepreneur', 'Индивидуальный предприниматель')], max_length=50, verbose_name='тип элемента'),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='house_number',
            field=models.CharField(max_length=10, verbose_name='номер дома'),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='level',
            field=models.PositiveSmallIntegerField(verbose_name='уровень'),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='street',
            field=models.CharField(max_length=100, verbose_name='улица'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='debt_to_supplier',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженность поставщика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=100, verbose_name='модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(verbose_name='дата выхода'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(max_length=50, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(max_length=50, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='house_number',
            field=models.CharField(max_length=10, verbose_name='номер дома'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='street',
            field=models.CharField(max_length=100, verbose_name='улица'),
        ),
    ]
