# Generated by Django 5.0.2 on 2024-02-17 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_networkelement_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkelement',
            options={'verbose_name': 'сеть', 'verbose_name_plural': 'сети'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'поставщик', 'verbose_name_plural': 'поставщики'},
        ),
        migrations.AddField(
            model_name='product',
            name='debt',
            field=models.BooleanField(default=False, verbose_name='Задолженность'),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='element_type',
            field=models.CharField(choices=[('Factory', 'Завод'), ('RetailNetwork', 'Розничная сеть'), ('IndividualEntrepreneur', 'Индивидуальный предприниматель')], max_length=50, verbose_name='тип элемента сети'),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='products',
            field=models.ManyToManyField(to='network.product', verbose_name='продукты'),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplied_to', to='network.supplier', verbose_name='поставщик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.supplier', verbose_name='поставщик'),
        ),
    ]
