# Generated by Django 5.0.2 on 2024-02-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_supplier_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkelement',
            name='debt',
            field=models.BooleanField(default=False, verbose_name='Задолженность'),
        ),
    ]
