# Generated by Django 5.0.2 on 2024-02-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_networkelement_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='debt_to_supplier',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженность перед поставщиком'),
        ),
    ]
